spring.application.name=moneywise-backend

# MySQL AlwaysData
spring.datasource.url=jdbc:mysql://mysql-gamerred4.alwaysdata.net:3306/gamerred4_moneywise
spring.datasource.username=gamerred4_moneywise
spring.datasource.password=redouane
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=0

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Schema initialization (desactivé, tables déjà créées sur AlwaysData)
spring.sql.init.mode=never

# Server
server.port=8081

# JWT
jwt.secret=Hh4c0SmnnbifHg9wzLTF5tyfEUm33nCpAvu/uJr0uek=
jwt.expiration=86400000

# CORS
cors.allowed-origins=https://redmoneywise.netlify.app

# Actuator (keep-alive ping pour Render)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Logging
logging.level.com.moneywise=INFO
